### ISSUE TITLE
Template T2 - Mantine Stack

### ISSUE THREAD

**Issue by CsarChvz** [drcan94/t2-mantine-stack#1]
Convert this repo into a simple stack!

Greate work @drcan94

**Comment by drcan94** [comment]
Thanks :)
You mean converting to run with cli ?

**Comment by drcan94** [comment]
> Convert this repo into a simple stack!
> 
> Greate work @drcan94 
> 

Thanks :)
You mean converting to run with cli ?

**Comment by drcan94** [comment]
> Convert this repo into a simple stack!
> 
> Greate work @drcan94 
> 

Thanks :)
You mean converting to run with cli ?
@CsarChvz

**Comment by CsarChvz** [comment]
Yep!
I would be great

**Comment by drcan94** [comment]
> Yep!
> I would be great

I don't know how i do that :) but if you know, you can fork and publish as a cli.. 
@CsarChvz
